import './globals.css'
import { Bungee } from 'next/font/google'

const bungee = Bungee({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bungee.className}>{children}</body>
    </html>
  )
}
